version: 2.1
orbs:
#   heroku: circleci/heroku@2.0
  node: circleci/node@5.1.0
#   #python: circleci/python@2.1.1

jobs:
  build:
    docker:
      - image: cimg/node:15.9.0
    steps:
      - checkout
    # build job ommitted for brevity
      - node/install-packages
      - run:
        command: npm run start
      - run:
        command: craco build
  deploy:
    docker:
      - image: cimg/node:15.9.0
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: heroku-deploy-setup # only run deploy-via-git job on main branch
