# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@2.0
  node:circleci/node@5.1.0
  #python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  connect-us-app:
    #executor: heroku/default

    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image

    
    steps:
      - checkout
      - node/install:
          install-packages: true
      - run: node --version
          #name: "Say hello"
          #command: "echo Hello, World!"
          #name: "NPM install"
          #command: npm install
          
      - run:
          command: craco build
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - connect-us-app
