version: 2.1
orbs:
  #heroku: circleci/heroku@2.0
  node: circleci/node@5.1.0
  #python: circleci/python@2.1.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:15.9.0

    executor: node/default 
 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
       
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            -

workflows:
  test_my_app:
    jobs:
      - build_and_test

