version: 2.1
orbs:
  heroku: circleci/heroku@2.0
  node: circleci/node@5.1.0
  #python: circleci/python@2.1.1

workflows:
  heroku_deploy:
    jobs:           
      - heroku/deploy-via-git:
          context: Heroku-Env-Vars
          pre-steps:
            #- checkout
            - node/install-packages
            - run:
              command: npm run start
            - run:
              command: craco build
          
jobs:
  heroku_deploy:
    docker:
      - image: cimg/node:15.9.0
    executor: node/default           


