version: 2.1
orbs:

  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0

jobs:
  build_and_build:
    docker:
      - image: cimg/node:15.9.0
    steps:
      
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      #- run:
          #name: frontend test
          #command: npm run test
      
      - run:
          name: frontend build
          command: npm run build
        
  deploy:

    docker:
      - image: cimg/node:15.9.0
    steps:
      - checkout

​​
​​      - heroku/deploy-via-git:
​​          app-name: renes-2024-connect-us 
​​          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git          
          name: Deploy Main to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  build-deploy:
    jobs:
      - build_and_build
      - deploy:
          context: herokuEnvVars
          requires:
            - build_and_build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: heroku-deploy-setup # only run deploy-via-git job on main branch
