version: 2.1

orbs:
  #heroku: circleci/heroku@2.0
  node: circleci/node@5.1.0
  #python: circleci/python@2.1.1
          

workflows:
  run-npm-command:
    jobs:
      - node/run:
        npm-run: build
