version: 2.1
orbs:
  #heroku: circleci/heroku@2.0
  node: circleci/node@5.1.0
  #python: circleci/python@2.1.1

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '15.9'
      - run: node --version

      - node/run:
          npm-run: build



workflows:
  test_my_app:
    jobs:
      - install-node-example
